language: ruby
os: linux
dist: bionic

ruby:
  - 2.3.0
  - 2.4.8
  - 2.5.0
  - 2.6.0
  - 2.7.8
  - 3.0.0
  
  
script:
- ruby -v
- bundle -v
- ruby -e 'puts "HEY PLANET"'
- rvm list
- gem install sinatra
- gem install rubocop
# - rvm get stable
#- rvm use 2.6.9


#- gem install bundler -v 2.3.26
#- rvm remove 2.6.9
#- ruby -v
#- rvm use 2.6.9 --install
#- ruby -v
#- ruby -e 'puts "HEY PLANET"'
#- gem install bundler -v 2.3.26


