language: ruby
os: linux
dist: focal
ruby:
  - 2.3.8
  - 2.4.0


install:
  - echo "deb http://security.ubuntu.com/ubuntu bionic-security main" | sudo tee -a /etc/apt/sources.list
  - sudo apt update
  - sudo apt-get install openssl
  - sudo apt-cache policy libssl1.0-dev
  - sudo apt-get install libssl1.0-dev
  
script: ruby -v
