jobs:
  include:
#     - arch: ppc64le
#       dist: xenial
#       group: test
#     - arch: ppc64le
#       dist: bionic
#       group: test
    - arch: amd64
      dist: focal
      group: stable
   



script:
  - uname -a
  - cat /etc/hosts
  - ls -lah /etc/cloud/cloud.cfg.d/
  - cat /etc/cloud/cloud.cfg
  - cat /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  - cat /etc/hosts 
  - sudo true
  - ping -c 3 localhost
#   - echo -n "127.0.0.1 localhost " | sudo tee -a /etc/hosts
#   - cat /etc/hosts 
#   - sudo true
  
