dist: jammy
group: edge

jobs:
  include:
    - arch: arm64
    - arch: ppc64le      
    - arch: s390x
    # - arch: amd64
    
# group: edge
language: java

# go:
# - master


script:
  - sudo apt-get update
  - cat /etc/hosts
