jobs:
  include:
    - os: osx
      osx_image: xcode13.1
    - os: osx
      osx_image: xcode13.1
    - os: osx
      osx_image: xcode13.1
    - os: osx
      osx_image: xcode13.1
    - os: osx
      osx_image: xcode13.1
    - os: osx
      osx_image: xcode13.1
    - os: osx
      osx_image: xcode13.1
    - os: osx
      osx_image: xcode13.1
    - os: osx
      osx_image: xcode13.1
      

script:
  - sw_vers
  - ls -lah /etc/ssl/
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - sleep 240
  - brew install curl htop bash
  
