jobs:
  include:
    - arch: ppc64le
      dist: xenial
    - arch: ppc64le
      dist: bionic
    - arch: ppc64le
      dist: focal
      group: test
   

language: java
jdk: openjdk8

script:
  - sudo apt list --installed
  - dpkg -l
