os: linux
arch: amd64
group: dev

language: ruby
ruby: 2.6.9


script: 
    - rvm list
    - ruby -v
    - gem install bundler -v 2.4.9

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy



