jobs:
  include:
    - arch: ppc64le
      dist: xenial
    - arch: ppc64le
      dist: bionic
      group: test
    - arch: ppc64le
      dist: focal

language: java
jdk: openjdk8

script:
  - mvn --version
