language: ruby

cache:
  bundler: true

services:
  - redis

dist: trusty

before_install:
  - python --version
  - python3 --version
#   - pip install awscli --user
  - python3 -m pip install awscli
