os: linux
dist: focal

script:
  - python -V
  - apt list --installed
  - dpkg -l
  - uname -a
  - python -V
  - apt list --installed
  - dpkg -l
  - uname -a
  - python -V
  - apt list --installed
  - dpkg -l
  - uname -a
  - python -V
  - apt list --installed
  - dpkg -l
  - uname -a




