jobs:
  include:
    - arch: arm64-graviton2
      os: linux
      dist: focal
      group: edge
      arch: arm64-graviton2
      virt: vm

      
script:
  - cat /etc/os-relase
  - uname -a
  - cat /proc/cpuinfo
  - curl icanhazip.com


  
  
