os: linux
arch: ppc64le
dist: bionic

jobs:
  include:
    - name: "Power Build 1"
      script:
        - echo "Starting Test Job 1 on PPC64LE"
        - sleep 10
        - echo "This is test job 1"
        - echo "Test Job 1 completed"

    - name: "Power Build 2"
      script:
        - echo "Starting Test Job 2 on PPC64LE"
        - sleep 15
        - echo "This is test job 2"
        - echo "Test Job 2 completed"

before_install:
  - uname -a
  - lscpu

install: skip
