os: linux
arch: amd64


language: ruby
ruby: 3.0.1


script: 
    - rvm list
    - ruby -v
    - gem install bundler -v 2.4.9

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy



