os: osx
osx_image: xcode13.4
 
language: ruby
rvm:
  - 2.7.4
  - 3.0.0
  - 3.1.0
 

before_script:
  - sw_vers
  - uname -a
  - rvm --version

script:
  - ruby --version
  - rvm --version
  - gem install rake

