
os: linux
arch: s390x
jobs:
  include:
    - script: sleep 120
    - script: sleep 120
    - script: sleep 120
    - script: sleep 120
    - script: sleep 120
    - script: sleep 120
    - script: sleep 120
