
jobs:
  include:
    - arch: s390x
      dist: bionic
    - arch: s390x
      dist: xenial      
    - arch: s390x
      dist: focal
    - arch: s390x
      dist: bionic
    - arch: s390x
      dist: xenial      
    - arch: s390x
      dist: focal
      

services:
  - postgresql

script:
  - uname -a 

