---
# dist: jammy
# language: go
# arch: arm64-graviton2
# virt: vm
# group: edge

os: linux
rvm: 2.5.8
language: ruby
dist: xenial

script:
  - uname -a
  - ls -ltrah /tmp
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  





