os: linux

group: edge

script:
  - ls -la $HOME
  - ls -lah /etc/cloud/cloud.cfg.d/
  - cat /etc/cloud/cloud.cfg
  - cat /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  - cat /etc/hosts
  - cloud-init status --long
  


language: java
# python:
#   - "3.8"

jobs:
  include:
    - arch: ppc64le
      dist: jammy
    # - arch: ppc64le
    #   dist: focal
    # xenial will be deprecated in future
    # - arch: ppc64le
    #   dist: xenial
