---
language: php
os:
- linux
dist: focal
sudo: true
php:
- '7.4'
services:
- mysql
script:
  - uname -a
  - curl -4 https://icanhazip.com/
  - cat /etc/hosts
  - ifconfig | grep mtu
  - ping -c 3 localhost



