---
dist: jammy
language: ruby
# arch: arm64-graviton2
# virt: vm
# group: edge


script:
  - uname -a
  - ls -ltrah /tmp
  - sudo apt-get update
  - sudo apt-get install libqt5webkit5-dev google-chrome-stable -y
  





