jobs:
  include:
    - arch: arm64
      dist: xenial
      group: stable
    - arch: arm64
      dist: bionic
      group: stable
    - arch: ppc64le
      dist: focal
      group: stable
   

language: java
jdk: openjdk8

script:
  - sudo apt list --installed
  - dpkg -l
