jobs:
  include:
    - arch: arm64-graviton2
      os: linux
      dist: jammy
      group: edge
      arch: arm64-graviton2
      virt: vm

      
script:
  - cat /etc/os-release
  #- cat /etc/hosts
  - dpl --version
  - uname -a
  - cat /proc/cpuinfo
  - curl icanhazip.com


  
  
