jobs:
  include:
    - arch: ppc64le
      dist: xenial
#       group: edge
    - arch: ppc64le
      dist: bionic
#       group: edge
    - arch: ppc64le
      dist: focal
#       group: edge

language: java
jdk: openjdk15

script:
  - mvn --version
