arch: ppc64le
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - linux: linux
      dist: focal

script:
  - echo $HOSTNAME
  - curl icanhazip.com
  - cat /etc/hosts
 
