arch: arm64
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - linux: linux
      dist: focal

script:
  - echo $HOSTNAME
  - curl icanhazip.com
  - cat /etc/hosts
  - sudo docker run -t ubuntu:18.04 bash -c 'apt update -y && apt install -y wget'
 
