language: ruby
os: linux
dist: bionic
group: edge

ruby:
  - 2.6.9
  - 3.0.0
# install:
#   - echo "deb http://security.ubuntu.com/ubuntu bionic-security main" | sudo tee -a /etc/apt/sources.list
#   - sudo apt update
#   - sudo apt-get install openssl -y 
#   - sudo apt-cache policy libssl1.0-dev
#   - sudo apt-get install libssl1.0-dev -y 
  
script:
- ruby -v
- rvm list
# - rvm get stable
- rvm use 2.6.9
- ruby -e 'puts "HEY PLANET"'
- gem install bundler -v 2.3.26
- rvm remove 2.6.9
- ruby -v
- rvm use 2.6.9 --install
- ruby -v
- ruby -e 'puts "HEY PLANET"'
- gem install bundler -v 2.3.26


