jobs:
  include:
    - arch: ppc64le
      dist: xenial
      group: test
    - arch: ppc64le
      dist: bionic
      group: test
    - arch: ppc64le
      dist: focal
      group: test
   



script:
  - uname -a
  - cat /etc/hosts
  - ls -lah /etc/cloud/cloud.cfg.d/
  - cat /etc/cloud/cloud.cfg
  - cat /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  - cat /etc/hosts  
  
