jobs:
  include:
    - arch: amd64
      dist: xenial
    - arch: amd64
      dist: bionic
    - arch: amd64
      dist: focal
    - arch: amd64
      dist: jammy
    - arch: s390x
      dist: bionic
    - arch: arm
      dist: bionic

   

language: python

script:
  - uname -a
  - python3 --version
  - python --version
  - apt-get update
  - apt-get install neovim
#   - ant -v
#   - cat /etc/hostname
#   - cat /etc/hosts
#   - cat /etc/nsswitch.conf
#   - cat /etc/resolv.conf
#   - getent hosts localhost.localdomain
#   - sudo true
#   - hostnamectl
#   - hostname
#   - ls -lah /etc/cloud/cloud.cfg.d/
#   - cat /etc/cloud/cloud.cfg
#   - cat /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
#   - cat /etc/hosts 
#   - sudo true
#   - ping -c 3 localhost
#   - echo -n "127.0.0.1 localhost " | sudo tee -a /etc/hosts
#   - cat /etc/hosts 
#   - sudo true
  
